### ISSUE TITLE
能否提升下watch的性能~

### ISSUE THREAD

**Issue by okoala** [fex-team/fis3-command-release#2]
每次修改一个文件，就会全体文件release一下。我试着在change的时候options.srcCache只传入当前改变的文件，性能立马有20x的提升。但是我不确定这么改是否有其他的问题~~

**Comment by oxUnd** [comment]
给个例子，我每次只修改的的编译啊

**Comment by okoala** [comment]
https://github.com/fex-team/fis3-command-release/blob/master/lib%2Fwatch.js#L179

@xiangshouding 我这边项目在运行到这的时候，options.srcCache 里有600多个文件~~不清楚是否正常~

![](http://i1.tietuku.com/f7a05fd83d86cd12.png)

**Comment by oxUnd** [comment]
@okoala  那你文件多少个啊，项目底下？

**Comment by okoala** [comment]
@xiangshouding 大体算了下，应该就是这个数了~~

**Comment by oxUnd** [comment]
@okoala OK，我们再研究研究这块是否还能继续优化。

**Comment by 2betop** [comment]
目前编译是走文件缓存 compare, 也许换成内存缓存会快不少

**Comment by jiangyuan** [comment]
我这里也遇到同样的问题了。
@xiangshouding 最近有搞起吗？

**Comment by jiangyuan** [comment]
我自己试着修改了下。
按照一楼所说：

``` js
options.srcCache = [path];
// ~options.srcCache.indexOf(path) || match(path) &&
//   (options.srcCache.push(path), modified = true);
```

挺顺畅，直到遇到了有 `inline` 的情况，这个时候关联到了两个文件。
现在的问题是怎样获取到当前修改的文件所 `link` 的文件。

查到 fis3 的 `compile.js` 里面，发现竟然没有将 `inline` 文件加入到 `file.links` ，很不解。

@2betop @xiangshouding 怎搞？

**Comment by oxUnd** [comment]
@jiangyuan 你是要干嘛？

**Comment by jiangyuan** [comment]
就是提升 watch 的性能啊。
每次 watch 不需要编译所有的文件，只要编译改动的文件及其相关的文件。

**Comment by 2betop** [comment]
没改动的文件都是走的缓存，编译时间很短的。按你说的那样做的话，packager 阶段一些打包插件会出现异常。

**Comment by jiangyuan** [comment]
@2betop 具体会有些什么问题呢？
其实在 `watch` 阶段，很少需要打包。

**Comment by jiangyuan** [comment]
上面我搞错了，inline 文件在 `compile` 的时候加入到了 `file.links` 。
现在的问题是在 watch 过程中要获取 `file.links` 。

**Comment by 2betop** [comment]
3.4.3 watch 做了很大的优化，已经不是全量了。
